workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Generate Gradle Wrapper 9.3.1
        script: |
          gradle wrapper --gradle-version 9.3.1
      - name: Move Keystore to App Folder
        script: |
          # Yeh step file ko sahi directory me copy kar dega taake Gradle ko mil jaye
          cp my-release-key.jks app/ || true
      - name: Build Android App Bundle (.aab)
        script: |
          chmod +x gradlew
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=my-release-key.jks \
            -Pandroid.injected.signing.store.password=admin204060@ \
            -Pandroid.injected.signing.key.alias=my-alias \
            -Pandroid.injected.signing.key.password=admin204060@
    artifacts:
      - app/build/outputs/bundle/release/*.aab
