workflows:
  android-release:
    name: Android Release Build
    instance_type: mac_mini_m1
    max_build_duration: 60
    environment:
      groups:
        - keystore_credentials
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: 'main'
    scripts:
      - name: Generate Gradle Wrapper 9.3.1
        script: |
          gradle wrapper --gradle-version 9.3.1
      - name: Decode New Keystore File
        script: |
          echo "$CM_KEYSTORE" | base64 --decode > /tmp/keystore.jks
      - name: Build Android App Bundle (.aab)
        script: |
          chmod +x gradlew
          ./gradlew bundleRelease \
            -Pandroid.injected.signing.store.file=/tmp/keystore.jks \
            -Pandroid.injected.signing.store.password=$CM_KEYSTORE_PASSWOR \
            -Pandroid.injected.signing.key.alias=$CM_KEY_ALIAS \
            -Pandroid.injected.signing.key.password=$CM_KEY_PASSWORD
    artifacts:
      - app/build/outputs/bundle/release/*.aab
